# Generated by Django 3.2.6 on 2022-05-03 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(help_text='Введите описание товара', max_length=1000, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Разместите фото для объявления', null=True, upload_to='ad/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Добавьте цену товара', null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Введите название товара', max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(help_text='Добавьте объявление, которое относится к комментарию', on_delete=django.db.models.deletion.CASCADE, to='ads.ad', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Выберите автора комментария', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(help_text='Введите время создания комментария', null=True, verbose_name='Время создания комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Оставьте свой комментарий здесь', max_length=500, verbose_name='Комментарий'),
        ),
    ]
