# Generated by Django 3.2.6 on 2022-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Укажите электронную почту', max_length=50, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите имя, макс 64 символа', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Укажите активен ли аккаунт', null=True, verbose_name='Аккаунт активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию, макс 64 символа', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Укажите телефон для связи', max_length=15, verbose_name='Укажите телефон для связи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', help_text='Укажите роль пользователя', max_length=9, verbose_name='Роль пользователя'),
        ),
    ]
